export const sidos = [
	{ "value": "11", "text": "서울특별시" },
	{ "value": "26", "text": "부산광역시" },
	{ "value": "27", "text": "대구광역시" },
	{ "value": "28", "text": "인천광역시" },
	{ "value": "29", "text": "광주광역시" },
	{ "value": "30", "text": "대전광역시" },
	{ "value": "31", "text": "울산광역시" },
	{ "value": "36", "text": "세종특별자치시" },
	{ "value": "41", "text": "경기도" },
	{ "value": "43", "text": "충청북도" },
	{ "value": "44", "text": "충청남도" },
	{ "value": "45", "text": "전라북도" },
	{ "value": "46", "text": "전라남도" },
	{ "value": "47", "text": "경상북도" },
	{ "value": "48", "text": "경상남도" },
	{ "value": "50", "text": "제주특별자치도" },
	{ "value": "51", "text": "강원특별자치도" }
];

export const sigungus = {
	"*": [],
	"11": [
		{ "value": "110", "text": "종로구" },
		{ "value": "140", "text": "중구" },
		{ "value": "170", "text": "용산구" },
		{ "value": "200", "text": "성동구" },
		{ "value": "215", "text": "광진구" },
		{ "value": "230", "text": "동대문구" },
		{ "value": "260", "text": "중랑구" },
		{ "value": "290", "text": "성북구" },
		{ "value": "305", "text": "강북구" },
		{ "value": "320", "text": "도봉구" },
		{ "value": "350", "text": "노원구" },
		{ "value": "380", "text": "은평구" },
		{ "value": "410", "text": "서대문구" },
		{ "value": "440", "text": "마포구" },
		{ "value": "470", "text": "양천구" },
		{ "value": "500", "text": "강서구" },
		{ "value": "530", "text": "구로구" },
		{ "value": "545", "text": "금천구" },
		{ "value": "560", "text": "영등포구" },
		{ "value": "590", "text": "동작구" },
		{ "value": "620", "text": "관악구" },
		{ "value": "650", "text": "서초구" },
		{ "value": "680", "text": "강남구" },
		{ "value": "710", "text": "송파구" },
		{ "value": "740", "text": "강동구" }
	],
	"26": [
		{ "value": "110", "text": "중구" },
		{ "value": "140", "text": "서구" },
		{ "value": "170", "text": "동구" },
		{ "value": "200", "text": "영도구" },
		{ "value": "230", "text": "부산진구" },
		{ "value": "260", "text": "동래구" },
		{ "value": "290", "text": "남구" },
		{ "value": "320", "text": "북구" },
		{ "value": "350", "text": "해운대구" },
		{ "value": "380", "text": "사하구" },
		{ "value": "410", "text": "금정구" },
		{ "value": "440", "text": "강서구" },
		{ "value": "470", "text": "연제구" },
		{ "value": "500", "text": "수영구" },
		{ "value": "530", "text": "사상구" },
		{ "value": "710", "text": "기장군" }
	],
	"27": [
		{ "value": "110", "text": "중구" },
		{ "value": "140", "text": "동구" },
		{ "value": "170", "text": "서구" },
		{ "value": "200", "text": "남구" },
		{ "value": "230", "text": "북구" },
		{ "value": "260", "text": "수성구" },
		{ "value": "290", "text": "달서구" },
		{ "value": "710", "text": "달성군" },
		{ "value": "720", "text": "군위군" }
	],
	"28": [
		{ "value": "110", "text": "중구" },
		{ "value": "140", "text": "동구" },
		{ "value": "177", "text": "미추홀구" },
		{ "value": "185", "text": "연수구" },
		{ "value": "200", "text": "남동구" },
		{ "value": "237", "text": "부평구" },
		{ "value": "245", "text": "계양구" },
		{ "value": "260", "text": "서구" },
		{ "value": "710", "text": "강화군" },
		{ "value": "720", "text": "옹진군" }
	],
	"29": [
		{ "value": "110", "text": "동구" },
		{ "value": "140", "text": "서구" },
		{ "value": "155", "text": "남구" },
		{ "value": "170", "text": "북구" },
		{ "value": "200", "text": "광산구" }
	],
	"30": [
		{ "value": "110", "text": "동구" },
		{ "value": "140", "text": "중구" },
		{ "value": "170", "text": "서구" },
		{ "value": "200", "text": "유성구" },
		{ "value": "230", "text": "대덕구" }
	],
	"31": [
		{ "value": "110", "text": "중구" },
		{ "value": "140", "text": "남구" },
		{ "value": "170", "text": "동구" },
		{ "value": "200", "text": "북구" },
		{ "value": "710", "text": "울주군" }
	],
	"36": [
		{"value": "110", "text": "세종특별자치시"}
	],
	"41": [
		{ "value": "110", "text": "수원시" },
		{ "value": "111", "text": "장안구" },
		{ "value": "113", "text": "권선구" },
		{ "value": "115", "text": "팔달구" },
		{ "value": "117", "text": "영통구" },
		{ "value": "130", "text": "성남시" },
		{ "value": "131", "text": "수정구" },
		{ "value": "133", "text": "중원구" },
		{ "value": "135", "text": "분당구" },
		{ "value": "150", "text": "의정부시" },
		{ "value": "170", "text": "안양시" },
		{ "value": "171", "text": "만안구" },
		{ "value": "173", "text": "동안구" },
		{ "value": "190", "text": "부천시" },
		{ "value": "210", "text": "광명시" },
		{ "value": "220", "text": "평택시" },
		{ "value": "250", "text": "동두천시" },
		{ "value": "270", "text": "안산시" },
		{ "value": "271", "text": "상록구" },
		{ "value": "273", "text": "단원구" },
		{ "value": "280", "text": "고양시" },
		{ "value": "281", "text": "덕양구" },
		{ "value": "285", "text": "일산동구" },
		{ "value": "287", "text": "일산서구" },
		{ "value": "290", "text": "과천시" },
		{ "value": "310", "text": "구리시" },
		{ "value": "360", "text": "남양주시" },
		{ "value": "370", "text": "오산시" },
		{ "value": "390", "text": "시흥시" },
		{ "value": "410", "text": "군포시" },
		{ "value": "430", "text": "의왕시" },
		{ "value": "450", "text": "하남시" },
		{ "value": "460", "text": "용인시" },
		{ "value": "461", "text": "처인구" },
		{ "value": "463", "text": "기흥구" },
		{ "value": "465", "text": "수지구" },
		{ "value": "480", "text": "파주시" },
		{ "value": "500", "text": "이천시" },
		{ "value": "550", "text": "안성시" },
		{ "value": "570", "text": "김포시" },
		{ "value": "590", "text": "화성시" },
		{ "value": "610", "text": "광주시" },
		{ "value": "630", "text": "양주시" },
		{ "value": "650", "text": "포천시" },
		{ "value": "670", "text": "여주시" },
		{ "value": "800", "text": "연천군" },
		{ "value": "820", "text": "가평군" },
		{ "value": "830", "text": "양평군" }
	],
	"43": [
		{ "value": "110", "text": "청주시" },
		{ "value": "111", "text": "상당구" },
		{ "value": "112", "text": "서원구" },
		{ "value": "113", "text": "흥덕구" },
		{ "value": "114", "text": "청원구" },
		{ "value": "130", "text": "충주시" },
		{ "value": "150", "text": "제천시" },
		{ "value": "720", "text": "보은군" },
		{ "value": "730", "text": "옥천군" },
		{ "value": "740", "text": "영동군" },
		{ "value": "745", "text": "증평군" },
		{ "value": "750", "text": "진천군" },
		{ "value": "760", "text": "괴산군" },
		{ "value": "770", "text": "음성군" },
		{ "value": "800", "text": "단양군" }
	],
	"44": [
		{ "value": "130", "text": "천안시" },
		{ "value": "131", "text": "동남구" },
		{ "value": "133", "text": "서북구" },
		{ "value": "150", "text": "공주시" },
		{ "value": "180", "text": "보령시" },
		{ "value": "200", "text": "아산시" },
		{ "value": "210", "text": "서산시" },
		{ "value": "230", "text": "논산시" },
		{ "value": "250", "text": "계룡시" },
		{ "value": "270", "text": "당진시" },
		{ "value": "710", "text": "금산군" },
		{ "value": "760", "text": "부여군" },
		{ "value": "770", "text": "서천군" },
		{ "value": "790", "text": "청양군" },
		{ "value": "800", "text": "홍성군" },
		{ "value": "810", "text": "예산군" },
		{ "value": "825", "text": "태안군" }
	],
	"45": [
		{ "value": "110", "text": "전주시" },
		{ "value": "111", "text": "완산구" },
		{ "value": "113", "text": "덕진구" },
		{ "value": "130", "text": "군산시" },
		{ "value": "140", "text": "익산시" },
		{ "value": "180", "text": "정읍시" },
		{ "value": "190", "text": "남원시" },
		{ "value": "210", "text": "김제시" },
		{ "value": "710", "text": "완주군" },
		{ "value": "720", "text": "진안군" },
		{ "value": "730", "text": "무주군" },
		{ "value": "740", "text": "장수군" },
		{ "value": "750", "text": "임실군" },
		{ "value": "770", "text": "순창군" },
		{ "value": "790", "text": "고창군" },
		{ "value": "800", "text": "부안군" }
	],
	"46": [
		{ "value": "110", "text": "목포시" },
		{ "value": "130", "text": "여수시" },
		{ "value": "150", "text": "순천시" },
		{ "value": "170", "text": "나주시" },
		{ "value": "230", "text": "광양시" },
		{ "value": "710", "text": "담양군" },
		{ "value": "720", "text": "곡성군" },
		{ "value": "730", "text": "구례군" },
		{ "value": "770", "text": "고흥군" },
		{ "value": "780", "text": "보성군" },
		{ "value": "790", "text": "화순군" },
		{ "value": "800", "text": "장흥군" },
		{ "value": "810", "text": "강진군" },
		{ "value": "820", "text": "해남군" },
		{ "value": "830", "text": "영암군" },
		{ "value": "840", "text": "무안군" },
		{ "value": "860", "text": "함평군" },
		{ "value": "870", "text": "영광군" },
		{ "value": "880", "text": "장성군" },
		{ "value": "890", "text": "완도군" },
		{ "value": "900", "text": "진도군" },
		{ "value": "910", "text": "신안군" }
	],
	"47": [
		{ "value": "110", "text": "포항시" },
		{ "value": "111", "text": "남구" },
		{ "value": "113", "text": "북구" },
		{ "value": "130", "text": "경주시" },
		{ "value": "150", "text": "김천시" },
		{ "value": "170", "text": "안동시" },
		{ "value": "190", "text": "구미시" },
		{ "value": "210", "text": "영주시" },
		{ "value": "230", "text": "영천시" },
		{ "value": "250", "text": "상주시" },
		{ "value": "280", "text": "문경시" },
		{ "value": "290", "text": "경산시" },
		{ "value": "730", "text": "의성군" },
		{ "value": "750", "text": "청송군" },
		{ "value": "760", "text": "영양군" },
		{ "value": "770", "text": "영덕군" },
		{ "value": "820", "text": "청도군" },
		{ "value": "830", "text": "고령군" },
		{ "value": "840", "text": "성주군" },
		{ "value": "850", "text": "칠곡군" },
		{ "value": "900", "text": "예천군" },
		{ "value": "920", "text": "봉화군" },
		{ "value": "930", "text": "울진군" },
		{ "value": "940", "text": "울릉군" }
	],
	"48": [
		{ "value": "120", "text": "창원시" },
		{ "value": "121", "text": "의창구" },
		{ "value": "123", "text": "성산구" },
		{ "value": "125", "text": "마산합포구" },
		{ "value": "127", "text": "마산회원구" },
		{ "value": "129", "text": "진해구" },
		{ "value": "170", "text": "진주시" },
		{ "value": "220", "text": "통영시" },
		{ "value": "240", "text": "사천시" },
		{ "value": "250", "text": "김해시" },
		{ "value": "270", "text": "밀양시" },
		{ "value": "310", "text": "거제시" },
		{ "value": "330", "text": "양산시" },
		{ "value": "720", "text": "의령군" },
		{ "value": "730", "text": "함안군" },
		{ "value": "740", "text": "창녕군" },
		{ "value": "820", "text": "고성군" },
		{ "value": "840", "text": "남해군" },
		{ "value": "850", "text": "하동군" },
		{ "value": "860", "text": "산청군" },
		{ "value": "870", "text": "함양군" },
		{ "value": "880", "text": "거창군" },
		{ "value": "890", "text": "합천군" }
	],
	"50": [
		{ "value": "110", "text": "제주시" },
		{ "value": "130", "text": "서귀포시" }
	],
	"51": [
		{ "value": "110", "text": "춘천시" },
		{ "value": "130", "text": "원주시" },
		{ "value": "150", "text": "강릉시" },
		{ "value": "170", "text": "동해시" },
		{ "value": "190", "text": "태백시" },
		{ "value": "210", "text": "속초시" },
		{ "value": "230", "text": "삼척시" },
		{ "value": "720", "text": "홍천군" },
		{ "value": "730", "text": "횡성군" },
		{ "value": "750", "text": "영월군" },
		{ "value": "760", "text": "평창군" },
		{ "value": "770", "text": "정선군" },
		{ "value": "780", "text": "철원군" },
		{ "value": "790", "text": "화천군" },
		{ "value": "800", "text": "양구군" },
		{ "value": "810", "text": "인제군" },
		{ "value": "820", "text": "고성군" },
		{ "value": "830", "text": "양양군" }
	]
};
